version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh:ro

    environment:
     - PORT=${PORT}
     - ACTIVE_POOL=${ACTIVE_POOL}
    command: ["/nginx-entrypoint.sh"]
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy